version: '3.8'

services:

  postgres:
    image: postgres:15.3-alpine3.18
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env
    restart: always
    networks:
      - app

  main:
    build:
      context: .
    env_file:
      - .env
    command: sh -c "
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000 & 
      python3 manage.py telegram"
    volumes:
      - .:/app:delegated
    ports:
      - ${PORT}:8000
    depends_on:
      - postgres
      - adminer
      # - redis
    networks:
      - app
    restart: always

networks:
  app:

volumes:
  pgdata: