# Generated by Django 5.2 on 2025-04-29 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dashboard', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description of the dashboard's purpose", null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the dashboard is active')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='light', help_text='Visual theme of the dashboard', max_length=50)),
                ('share_token', models.CharField(blank=True, help_text='Token for sharing the dashboard', max_length=100, null=True, unique=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Whether the dashboard is shared with others')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_date'],
            },
        ),
    ]
