# Generated by Django 5.2 on 2025-04-29 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(help_text='ID from the ChatGPT API', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name of the assistant', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Purpose and capabilities of the assistant', null=True)),
                ('assistant_type', models.CharField(choices=[('general', 'General Assistant'), ('coding', 'Coding Assistant'), ('writing', 'Writing Assistant'), ('analysis', 'Data Analysis'), ('custom', 'Custom Assistant')], default='general', help_text='Type of assistant', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this assistant was used', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the assistant is active')),
                ('config', models.JSONField(default=dict, help_text='Configuration settings for the assistant')),
                ('instructions', models.TextField(blank=True, help_text='Custom instructions for the assistant', null=True)),
                ('model', models.CharField(default='gpt-4', help_text='Underlying model used by the assistant', max_length=50)),
                ('dashboard', models.ForeignKey(help_text='Dashboard this assistant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='chatbot.dashboard')),
            ],
            options={
                'verbose_name': 'AI Assistant',
                'verbose_name_plural': 'AI Assistants',
                'ordering': ['name'],
            },
        ),
    ]
