# Generated by Django 5.2 on 2025-04-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_messanger'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='messanger',
            constraint=models.UniqueConstraint(fields=('dashboard', 'messanger_type'), name='unique_dashboard_messanger_type'),
        ),
        migrations.AddConstraint(
            model_name='messanger',
            constraint=models.UniqueConstraint(fields=('messanger_type', 'token'), name='unique_messanger_type_token'),
        ),
    ]
