# Generated by Django 5.2 on 2025-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_client_chat_message_messenger_chat_messenger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiassistant',
            options={'verbose_name': 'AI Assistant', 'verbose_name_plural': 'AI Assistants'},
        ),
        migrations.RemoveField(
            model_name='aiassistant',
            name='name',
        ),
        migrations.AlterField(
            model_name='aiassistant',
            name='model',
            field=models.CharField(default='gpt-4-turbo', help_text='Underlying model used by the assistant', max_length=50),
        ),
    ]
