# Generated by Django 5.2 on 2025-05-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_message_options_chat_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
