# Generated by Django 5.2 on 2025-05-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_chat_updated_date_message_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistant',
            name='instructions',
            field=models.TextField(default='You are our AI Assistant', help_text='Custom instructions for the assistant'),
        ),
    ]
