# Generated by Django 5.2 on 2025-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_aiassistant_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-created_date', '-updated_date')},
        ),
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('photo', 'Photo'), ('audio', 'Audio'), ('voice', 'Voice')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('messenger', 'client')},
        ),
    ]
