# Generated by Django 5.2 on 2025-05-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
